# istio-config.yaml

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: my-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*"
    ports:
    - number: 80
      protocol: HTTP
      name: http
      targetPort: 8080
    - number: 81
      protocol: HTTP
      name: http
      targetPort: 8081

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice-1
spec:
  hosts:
    - "microservice-1"
  gateways:
    - my-gateway
  http:
    - route:
        - destination:
            host: microservice-1
            port:
              number: 80


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice-2
spec:
  hosts:
    - "microservice-2"
  gateways:
    - my-gateway
  http:
    - route:
        - destination:
            host: microservice-2
            port:
              number: 81
