apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice-1
spec:
  hosts:
    - "microservice-1"
  http:
    - route:
        - destination:
            host: microservice-1
            subset: v1
            port:
              number: 80
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice-2
spec:
  hosts:
    - "microservice-2"
  http:
    - route:
        - destination:
            host: microservice-2 # The Target DNS name
            subset: v1
            port:
              number: 81
              # The name defined in the DestinationRule
          weight: 100
        - destination:
            host: microservice-2 # The Target DNS name
            subset: v2
            port:
              number: 81 # The name defined in the DestinationRule
          weight: 0

---

kind: DestinationRule       # Defining which pods should be part of each subset
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-microservice-2 # This can be anything you like.
  namespace: default
spec:
  host: microservice-2 # Service
  subsets:
    - labels:   # SELECTOR.
        version: v1 # find pods with label "v1"
      name: v1
    - labels:
        version: v2
      name: v2