apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
  namespace: default
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: microservice
spec:
  hosts:
  - "*"
  gateways:
    - ingress-gateway-configuration
  http:
  - name: "microservice-1-routes"
    match:
    - uri:
        prefix: "/m1"
    route:
    - destination:
        host: "microservice-1"
        subset: test4
        port:
          number: 3000
  - name: "microservice-2-routes"
    match:
    - uri:
        prefix: "/m2"
    route:
    - destination:
        host: "microservice-2"
        subset: test2
        port:
          number: 3001

---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-microservice-1
  namespace: default
spec:
  host: microservice-1
  subsets:
    - labels:
        version: test4
      name: test4
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: grouping-rules-for-microservice-2
  namespace: default
spec:
  host: microservice-2
  subsets:
    - labels:
        version: test2
      name: test2

